function data()
return {
	en = {

		["mod_name"] = "Car Transport Waggon DB",
		["mod_desc"] = "The car industries had an output of more and more cars so the transport with simple flat waggons wasn't effective anymore. So this was the time for the development of the first specialized car transport waggons at the Deutsche Bundesbahn. First they have been manufactured from other freight waggons, later there have been special manufactured cars to fit the newer and bigger cars. This mod contains waggons from 1938 up to current date. All cars are loading passengers and goods, fake versions can be also enabled via mod options.",

        ["Use_Fake"] = "Activate fake versions?",
        ["Use_Loaded"] = "Activate always full loaded versions?",
        ["option_autotransport_fake_desc"] = "This option determines if the fake version of all cars are shown in the game or not. Fake versions are waggons which have no function or costs but can be placed on rails for esthetical reasons.",
        ["option_autotransport_loaded_desc"] = "This option determines whether versions should be displayed in the game that are always permanently loaded with cars. These are located in an extra menu.",

        ["autotransport_menu"] = "Car transport waggons",
        ["autotransport_beladen_menu"] = "Car transport waggons (always loaded)",
        ["autotransport_fake_menu"] = "Car transport waggons (FAKE)",

        ["Fake"] = " (empty)",
        ["loaded"] = " (loaded)",

        ["Flachwagen_name"] = "flat car (empty)",
        ["Flachwagen_desc"] = "The first automobiles have been transported by railroad on simple flat waggons. The capacity was not too great. Flat waggon for 2 cars, empty.",
        ["Flachwagen_loaded_name"] = "flat car (loaded)",
        ["Flachwagen_loaded_desc"] = "The first automobiles have been transported by railroad on simple flat waggons. The capacity was not too great. Flat waggon loaded with 2 cars.",
		["Laaers560_menu_name"] = "Car transport Laaers 560 DB",
        ["Laaers560_name"] = "Laaers 560 DB (empty)",
        ["Laaers560_desc"] = "Car transport waggon of series Laaers 560.1. These waggons have two levels and can be used europe wide. Without load their maximum speed is allowed 120 km/h.",
        ["Laaers560_loaded"] = "Laaers 560 DB (loaded)",
        ["Laaers560_loaded_name"] = "Laaers 560 DB (loaded)",
        ["Laaers560_loaded_desc"] = "Car transport waggon of series Laaers 560.1. These waggons have two levels and can be used europe wide. Loaded with cars their maximum speed is allowed 100 km/h",
        ["Off52_menu_name"] = "Car transport Off 52 DB",
        ["Off52_name"] = "Off 52 DB (empty)",
        ["Off52_desc"] = "After the car industries have been growing and more and more cars had to be transported, it got uneconomally to use flat cars with one level. So begin of the 1950\'s the Deutsche Bundesbahn was building two-level waggons from bulk waggons. 1953 the Off 52 got in service.",
        ["Off52_loaded_name"] = "Off 52 DB (loaded)",
        ["Off52_loaded_desc"] = "After the car industries have been growing and more and more cars had to be transported, it got uneconomally to use flat cars with one level. So begin of the 1950\'s the Deutsche Bundesbahn was building two-level waggons from bulk waggons. 1953 the Off 52 got in service. Waggon is loaded with cars from type VW Beetle (\"Kaefer\").",
        ["Laae540"] = "Laae 540 DB (empty)",
        ["Laae540_name"] = "Laae 540 DB (empty)",
        ["Laae540_desc"] = "The original named Off 52 got renumbere to Laae 540 and stayed in service until all of them were retired in 1986.",
        ["Laae540_loaded"] = "Laae 540 DB (loaded)",
        ["Laae540_loaded_name"] = "Laae 540 DB (loaded)",
        ["Laae540_loaded_desc"] = "The original named Off 52 got renumbere to Laae 540 and stayed in service until all of them were retired in 1986. Unit is loaded with cars from type VW Beetle (\"Kaefer\").",
        ["Offs55"] = "Offs 55 DB (empty)",
        ["Offs55_name"] = "Offs 55 DB (empty)",
        ["Offs55_desc"] = "The first specifically designed car transport waggons of Deutsche Bundesbahn went in service in 1955. They were designed to haul at least at the upper level a tranporter like VW T1 (\"Bulli\"). The waggons were used in full trains with up to 25 units.",
        ["Offs55_loaded"] = "Offs 55 DB (loaded)",
        ["Offs55_loaded_name"] = "Offs 55 DB (loaded)",
        ["Offs55_loaded_desc"] = "The first specifically designed car transport waggons of Deutsche Bundesbahn went in service in 1955. They were designed to haul at least at the upper level a tranporter like VW T1 (\"Bulli\"). The waggons were used in full trains with up to 25 units",
        ["Laes542"] = "Laes 542 DB (empty)",
        ["Laes542_name"] = "Laes 542 DB (empty)",
        ["Laes542_desc"] = "The Offs 55 series got renumbered to Laes 542 in 1964, also the lower level got a full metal plate. They were retired from 1986, in 1997 the last waggon went out of service.",
        ["Laes542_loaded"] = "Laes 542 DB (loaded)",
        ["Laes542_loaded_name"] = "Laes 542 DB (loaded)",
        ["Laes542_loaded_desc"] = "The Offs 55 series got renumbered to Laes 542 in 1964, also the lower level got a full metal plate. They were retired from 1986, in 1997 the last waggon went out of service.",
        ["Laeqrss550"] = "Laeqrss 550 DB (empty)",
        ["Laeqrss550_name"] = "Laeqrss 550 DB (empty)",
        ["Laeqrss550_desc"] = "From 1963 the Offs 55 got equipped with heat pipes and ramps to be used in passenger trains. These units were name series Laeqrss 550 and had a maximum speed of 120 km/h.",
        ["Laeqrss550_loaded"] = "Laeqrss 550 DB (loaded)",
        ["Laeqrss550_loaded_name"] = "Laeqrss 550 DB (loaded)",
        ["Laeqrss550_loaded_desc"] = "From 1963 the Offs 55 got equipped with heat pipes and ramps to be used in passenger trains. These units were name series Laeqrss 550 and had a maximum speed of 120 km/h.",
        ["DDm915_menu_name"] = "Car transport DDm 915",
        ["DDm915_gruen"] = "DDm 915 DB (empty)",
        ["DDm915_gruen_name"] = "DDm 915 DB (empty)",
        ["DDm915_gruen_desc"] = "After the first series of rebuild freight waggons and the first bi-level cars with a maximum speed for freight trains, in the 1960\'s the first waggons with a maximum speed for use in express trains went in service. Technically these units were numbered as baggage cars. They were used in all kind of trains. The first units had been painted in the usual chromoxid green.",
        ["DDm915_gruen_loaded"] = "DDm 915 DB (loaded)",
        ["DDm915_gruen_loaded_name"] = "DDm 915 DB (loaded)",
        ["DDm915_gruen_loaded_desc"] = "After the first series of rebuild freight waggons and the first bi-level cars with a maximum speed for freight trains, in the 1960\'s the first waggons with a maximum speed for use in express trains went in service. Technically these units were numbered as baggage cars. They were used in all kind of trains. The first units had been painted in the usual chromoxid green.",
        ["DDm915_fernblau_name"] = "DDm 915 DB (empty)",
        ["DDm915_fernblau_desc"] = "After the first series of rebuild freight waggons and the first bi-level cars with a maximum speed for freight trains, in the 1960\'s the first waggons with a maximum speed for use in express trains went in service. Technically these units were numbered as baggage cars. They were used in all kind of trains. With the new orient red color code the livery changed to blue as in the InterRegio.",
        ["DDm915_fernblau_loaded"] = "DDm 915 DB (loaded)",
        ["DDm915_fernblau_loaded_name"] = "DDm 915 DB (loaded)",
        ["DDm915_fernblau_loaded_desc"] = "After the first series of rebuild freight waggons and the first bi-level cars with a maximum speed for freight trains, in the 1960\'s the first waggons with a maximum speed for use in express trains went in service. Technically these units were numbered as baggage cars. They were used in all kind of trains. With the new orient red color code the livery changed to blue as in the InterRegio.",
        ["DDm915_verkehrsrot_name"] = "DDm 915 DB (empty)",
        ["DDm915_verkehrsrot_desc"] = "After the first series of rebuild freight waggons and the first bi-level cars with a maximum speed for freight trains, in the 1960\'s the first waggons with a maximum speed for use in express trains went in service. Technically these units were numbered as baggage cars. They were used in all kind of trains. Changing the ownership to sub-company DB AutoZug they livery were changed to traffic red.",
        ["DDm915_verkehrsrot_loaded_name"] = "DDm 915 DB (loaded)",
        ["DDm915_verkehrsrot_loaded_desc"] = "After the first series of rebuild freight waggons and the first bi-level cars with a maximum speed for freight trains, in the 1960\'s the first waggons with a maximum speed for use in express trains went in service. Technically these units were numbered as baggage cars. They were used in all kind of trains. Changing the ownership to sub-company DB AutoZug they livery were changed to traffic red.",
        ["Laes548"] = "Laes 548 DB (empty)",
        ["Laes548_loaded"] = "Laes 548 DB (loaded)",
        ["WesterlandEinheit_name"] = "Laes 549 DB (\"Westerland unit\") (empty)",
        ["WesterlandEinheit_desc"] = "The so called \"Westerland unit\" is a unit consistig of 11 parts for DB Autozug across the Hindenburgdamm to Sylt island. At each end there is a portal waggon, which has the ability to load cars from the side. In the middle is a 9-parts unit of bi-level waggons.",
        ["WesterlandEinheit_loaded_name"] = "Laes 549 DB (\"Westerland unit\") (loaded)",
        ["Laeqrss548_name"] = "Laeqrss 548 DB (empty)",
        ["Laeqrss548_desc"] = "The Laeqrss 548 was a series of 2-parts car transport units, which has been built from 1964. With the corresponding intermediate waggons they were the base for the so called \"Westerland unit\". These cars have been used same in passenger as in freight services.",
        ["Laeqrss548_loaded_name"] = "Laeqrss 548 DB (loaded)",
        ["Laeqrss548_loaded_desc"] = "The Laeqrss 548 was a series of 2-parts car transport units, which has been built from 1964. With the corresponding intermediate waggons they were the base for the so called \"Westerland unit\". These cars have been used same in passenger as in freight services.",
        ["Offhs66_name"] = "Offhs 66 DB (empty)",
        ["Offhs66_desc"] = "The waggons have been rebuild from the Rlmms 58 freight waggons and are used as portal waggons in the \"Westerland unit\", to allow side loading with the cars. For variety in the game these waggon is made standalone here as well.",
        ["Offhs66_loaded_name"] = "Offhs 66 DB (loaded)",
        ["Offhs66_loaded_desc"] = "The waggons have been rebuild from the Rlmms 58 freight waggons and are used as portal waggons in the \"Westerland unit\", to allow side loading with the cars. For variety in the game these waggon is made standalone here as well.",
        ["Leeks544_name"] = "Leeks 544 DB (empty)",
        ["Leeks544_desc"] = "From 1964 the Offhs 66 were named Leeks 544. The only function was still the same, the use as portal waggon in the \"Westerland unit\". For variety in the game these waggon is made standalone here as well.",
        ["Leeks544_loaded_name"] = "Leeks 544 DB (loaded)",
        ["Leeks544_loaded_desc"] = "From 1964 the Offhs 66 were named Leeks 544. The only function was still the same, the use as portal waggon in the \"Westerland unit\". For variety in the game these waggon is made standalone here as well.",
        ["Hccrss328"] = "Hccrss 328",
        ["Hccrss328_name"] = "Hccrss 328 (car transport)",
        ["Hccrss328_desc"] = "The two-parted car transport unit has been produced in 2013 for the first time. The waggons transport cars under a cover with a total weight of 2.8 tons each. The cars have lifting an lowering devices, the roof can be lifted for loading and unloading the upper floor. They are typically use in trains with only these waggons.",
        ["Hccrss5_870"] = "Hccrrs 5.870",
        ["Hccrss5_870_name"] = "Hccrrs 5.870 (car transport)",
        ["Hccrss5_870_desc"] = "The two-parted car transport unit is in use at the company ARS Altmann since 2010. The waggons transport cars under a cover with a total weight of 2.8 tons each. The cars have lifting an lowering devices, the roof can be lifted for loading and unloading the upper floor. They are typically use in trains with only these waggons.",

		["None"] = "None",
		["mw_model"] = "Car transport wagon",
		["mw_height"] = "Height",
		["mw_model_car"] = "Selection of different cars",
		["mw_loading"] = "Wagon load",
		["mw_loading_upper"] = "Upper deck", 
		["mw_loading_lower"] = "Lower deck",
		["mw_loading_both"] = "Both",
		["mw_random"] = "Random",
		["mw_astra"] = "Opel Astra",
		["mw_kadett"] = "Opel Kadett E",
		["mw_beetle"] = "VW Beetle",
		["mw_golf"] = "VW Golf I",
		["mw_santana"] = "VW Santana",
		["mw_touran"] = "VW Touran",
		["mw_trabant"] = "Trabant 601",
		["mw_lada"] = " Lada VAZ 2107",
		["mw_corolla"] = "Toyota Corolla",
		["mw_renault"] = "Renault F4",
		["mw_model_tooltip"] =  "Selection of different types of Car transport wagons: \n \n".. 
								"Image 01 = DDm915_fernblau \n" ..
								"Image 02 = DDm915_oebbDDm915_gruen \n" ..
								"Image 03 = DDm915_oebb \n" ..
								"Image 04 = DDm915_verkehrsrot \n" ..
								"Image 05 = Flachwagen \n" ..
								"Image 06 = Hccrss328 \n" ..
								"Image 07 = Hccrss328_ars \n" ..
								"Image 08 = Laae540 \n" ..
								"Image 09 = Laaers560 \n" ..
								"Image 10 = Laeqrss548 \n" ..
								"Image 11 = Laeqrss550 \n" ..
								"Image 12 = Laes542 \n" ..
								"Image 13 = Laes547 \n" ..
								"Image 14 = Leeks544 \n" ..
								"Image 15 = Off52 \n" ..
								"Image 16 = Offhs66 \n" ..
								"Image 17 = Offs55 \n",
		["mw_model_car_color"] =  "Colour Selection",
		["mw_model_car_color_tooltip"] =  "this selection only works if the car selection is not \"random\". \n \n",
		["mw_color1"] = "Colour 1",
		["mw_color2"] = "Colour 2",
		["mw_color3"] = "Colour 3",
		["mw_color4"] = "Colour 4",
		["mw_color5"] = "Colour 5",
		["mw_color6"] = "Colour 6",
		["mw_color7"] = "Colour 7",
		["mw_model_car_tooltip"] =  "Selection of the loaded cars depending on the selected car transport wagon \n"..
									"Not every car can be selected for the corresponding wagons. \n",
		["mw_move_tooltip"] =  "This allows the carriages to be shifted slightly to the left or right.",
		["mw_move"] =  "move",
		["mw_move_zmeter"] =  "in centimeters",
		["mw_left"] =  "left",
		["mw_right"] =  "right",
	},
	de = {

		["mod_name"] = "Autotransportwagen DB",
		["mod_desc"] = "Die Autoindustrie hat immer mehr Fahrzeuge hergestellt, so dass der Transport auf einfachen Flachwagen Anfang der 50er Jahre unwirtschaftlich wurde. Das war der Beginn der Entwicklung der speziellen Gattung der Autotransportwagen in Deutschland. Anfangs entstanden sie aus Umbauten von anderen Wagen, später dann auch immer spezialisierter um auch den gestiegenen Anforderungen an die neuen, größeren Autos zu folgen. Dieser Mod enthält die Fahrzeuge ab 1938 bis zum aktuellen Zeitpunkt. Alle Wagen transportieren Personen oder Güter. Fake Versionen können per Modoption aktiviert werden.",

        ["Use_Fake"] = "Fake-Versionen aktivieren?",
        ["Use_Loaded"] = "Immer vollbeladene Versionen aktivieren?",
        ["option_autotransport_fake_desc"] = "Diese Option legt fest, ob die Fake-Versionen angezeigt werden sollen im Spiel. Fake-Versionen sind Fahrzeuge ohne Funktion und Unterhaltskosten, die z.B. für Schönbau auf Gleisen abgestellt werden können.",
        ["option_autotransport_loaded_desc"] = "Diese Option legt fest, ob Versionen angezeigt werden sollen im Spiel, die immer fest mit Autos beladen sind. Diese sind in einem extra Menü untergebracht.",

        ["autotransport_menu"] = "Autotransportwagen",
        ["autotransport_beladen_menu"] = "Autotransportwagen (immer beladen)",
        ["autotransport_fake_menu"] = "Autotransportwagen (FAKE)",

        ["Fake"] = " (leer)",
        ["loaded"] = " (beladen)",

        ["Flachwagen_name"] = "Flachwagen",
        ["Flachwagen_desc"] = "Die ersten Automobile wurden auf der Eisenbahn auf einfachen flachen Wagen transportiert. Die Kapazität war nicht wirklich großartig. Flachwagen für 2 Autos.",
        ["Laaers560_name"] = "Laaers 560 DB",
        ["Laaers560_desc"] = "Autotransportwagen der Gattung Laaers 560.1. Diese Wagen haben zwei Ladeebenen und können europaweit eingesetzt werden. Unbeladen sind sie für eine Geschwindkeit von 120 km/h zugelassen.",
        ["Off52_name"] = "Off 52 DB",
        ["Off52_desc"] = "Nachdem die Autoindustrie immer mehr gewachsen war, wurde der Transport von Automobilen auf Flachwagen unwirtschaftlich und so enstanden Anfang der 1950er Jahre die ersten doppelstöckigen Autotransportwagen aus umgebauten Schüttgutwagen. Ab 1953 wurde die Serie Off 52 in Dienst gestellt.",
        ["Laae540_name"] = "Laae 540 DB",
        ["Laae540_desc"] = "Die seit 1953 in Dienst gestellten Off 52 wurden später mit Computernummer zu Laae 540 umgezeichnet und waren noch einige Jahre in Dienst, bis alle 1986 ausgemustert waren.",
        ["Offs55_name"] = "Offs 55 DB",
        ["Offs55_desc"] = "Die ersten eigens entwickelten Autotransportwagen der Deutschen Bundesbahn wurden 1955 in Dienst gestellt. Sie waren insbesondere darauf hin entwickelt, zumindest im Oberdeck einen Kleintransporter vom Format VW T1 (\"Bulli\") zu transportieren. Die Wagen wurden in Ganzzügen mit bis zu 25 Wagen eingesetzt.",
        ["Laes542_name"] = "Laes 542 DB",
        ["Laes542_desc"] = "Die Offs 55 wurden ab 1964 in Laes 542 umgezeichnet, außerdem wurden die untere Ladeebene mit Blechen verplankt seitlich. Ab 1986 begann die Ausmusterung, bis 1997 waren keine Wagen mehr im Bestand.",
        ["Laeqrss550_name"] = "Laeqrss 550 DB",
        ["Laeqrss550_desc"] = "Ab 1963 wurden Offs 55 teilweise mit Heizleitungen und Überfahrrampen ausgestattet, um sie auch in Personenzügen einsetzen zu können. Die Wagen wurden als Laeqrss 550 bezeichnet und waren für eine Höchstgeschwindigkeit von bis zu 120 km/h zugelassen.",
        ["DDm915_gruen_name"] = "DDm 915 DB",
        ["DDm915_gruen_desc"] = "Nach der ersten Entwicklung von umgebauten Güterzugwagen und Wagen, deren Geschwindigkeit an Güterzüge angepaßt war, wurde mitte der 1960er Jahre die ersten Wagen in Dienst gestellt, deren Höchstgeschwindigkeit an Schnellzüge angepaßt war. Technisch wurden diese Wagen als Gepäckwagen eingeordnet. Sie wurden in allen Arten von Zügen verwendet. Anfangs wurden die Wagen im typischen chromoxidgrün lackiert.",
        ["DDm915_fernblau_name"] = "DDm 915 DB",
        ["DDm915_fernblau_desc"] = "Nach der ersten Entwicklung von umgebauten Güterzugwagen und Wagen, deren Geschwindigkeit an Güterzüge angepaßt war, wurde mitte der 1960er Jahre die ersten Wagen in Dienst gestellt, deren Höchstgeschwindigkeit an Schnellzüge angepaßt war. Technisch wurden diese Wagen als Gepäckwagen eingeordnet. Sie wurden in allen Arten von Zügen verwendet. Lackiert wurden die Wagen mit Einführung des orientroten Farbschemas in fernblau wie die InterRegio.",
        ["DDm915_verkehrsrot_name"] = "DDm 915 DB",
        ["DDm915_verkehrsrot_desc"] = "Nach der ersten Entwicklung von umgebauten Güterzugwagen und Wagen, deren Geschwindigkeit an Güterzüge angepaßt war, wurde mitte der 1960er Jahre die ersten Wagen in Dienst gestellt, deren Höchstgeschwindigkeit an Schnellzüge angepaßt war. Technisch wurden diese Wagen als Gepäckwagen eingeordnet. Sie wurden in allen Arten von Zügen verwendet. Mit DB AutoZug wurden die Wagen im aktuellen verkehrsrot lackiert.",
        ["DDm915_oebb_name"] = "DDm 915 ÖBB",
        ["DDm915_oebb_desc"] = "Wagen für den Einsatz im RailJet.",
        ["Laes548"] = "Laes 548 DB",
        [" WesterlandEinheit_name"] = "Laes 549 DB (\"Westerland-Einheit\")",
        [" WesterlandEinheit_desc"] = "Die sogenannte \"Westerland-Einheit\" ist eine 11-teilige Einheit, die für den DB Autozug auf dem Hindenburgdamm nach Sylt zusammengestellt sind. Am den Enden befindet sich jeweils ein Portalwagen, damit die Wagen seitlich beladen werden können. In der Mitte ist eine 9-teilige Einheit mit Doppelstockwagen eingestellt.",
        ["Laeqrss548_name"] = "Laeqrss 548 DB",
        ["Laeqrss548_desc"] = "Die Laeqrss 548 waren eine zwei-teilige Autotransport-Einheit, die ab 1964 gebaut wurden. Mit entsprechenden Mittelwagen wurde daraus auch die sogenannte \"Westerland-Einheit\" abgeleitet. Diese Wagen wurden sowohl in Personenzügen verwendet, als Laes 547 auch in Güterzügen.",
        ["Laes547_name"] = "Laes 547 DB",
        ["Laes547_desc"] = "Die Laes 547 waren eine zwei-teilige Autotransport-Einheit, die ab 1964 gebaut wurden. Mit entsprechenden Mittelwagen wurde daraus auch die sogenannte \"Westerland-Einheit\" abgeleitet. Diese Wagen wurden sowohl in Güterzügen verwendet, als Laeqrss 548 auch in Personenzügen.",
        ["Offhs66_name"] = "Offhs 66 DB",
        ["Offhs66_desc"] = "Die Wagen wurden aus Rlmms 58 Güterwagen umgebaut und erfüllten den Zweck als Portalwagen in der \"Westerland-Einheit\", damit die Züge seitlich beladen werden konnten.Um andere Zugzusammenstellungen zu ermöglichen, gibt es diese Wagen auch einzeln im Spiel.",
        ["Leeks544_name"] = "Leeks 544 DB",
        ["Leeks544_desc"] = "Ab 1964 wurden die ehemaligen Offhs 66 als Leeks 544 bezeichnet. Ihre einzige Funktion ist die der Portalwagen in der \"Westerland-Einheit\". Um andere Zugzusammenstellungen zu ermöglichen, gibt es diese Wagen auch einzeln im Spiel.",
        ["Hccrss328_name"] = "Autotransport Hccrrs 328",
        ["Hccrss328_desc"] = "Die gedeckte zweiteilige Autotransportwageneinheit wurde 2013 erstmalig beschafft. Die Wagen ermöglichen den geschützten Transport von Fahrzeugen mit einem Gesamtgewicht von je bis zu 2,8 Tonnen. Die Wagen verfügen über Hebe- und Senkeinrichtungen zum Verstellen des Daches sowie der oberen Ladeebene zur Be- und Entladung der Kfz. Sie werden normalerweise artrein in Ganzzügen eingesetzt.",
        ["Hccrss5_870_name"] = "Autotransport Hccrrs 5.870",
        ["Hccrss5_870_desc"] = "Die gedeckte zweiteilige Autotransportwageneinheit wird seit 2010 bei der Firma ARS Altmann eingesetzt. Die Wagen ermöglichen den geschützten Transport von Fahrzeugen mit einem Gesamtgewicht von je bis zu 2,8 Tonnen. Die Wagen verfügen über Hebe- und Senkeinrichtungen zum Verstellen des Daches sowie der oberen Ladeebene zur Be- und Entladung der Kfz. Sie werden normalerweise artrein in Ganzzügen eingesetzt.",
		
		["None"] = "Keine",
		["mw_model"] = "Autotransportwagen",
		["mw_height"] = "Höhe",
		["mw_model_car"] = "Auswahl PKW",
		["mw_loading"] = "Beladung",
		["mw_loading_upper"] = "Oberdeck", 
		["mw_loading_lower"] = "Unterdeck",
		["mw_loading_both"] = "Beide",
		["mw_random"] = "Zufall",
		["mw_opel"] = "Opel Limosine",
		["mw_kadett"] = "Opel Kadett ",
		["mw_beetle"] = "VW Käfer",
		["mw_golf"] = "VW Golf I",
		["mw_santana"] = "VW Santana",
		["mw_touran"] = "VW Touran",
		["mw_trabant"] = "Trabant 601",
		["mw_lada"] = " Lada Niva 2107",
		["mw_corolla"] = "Toyota Corolla",
		["mw_renault"] = "Renault F4",
		["mw_model_tooltip"] =  "verschiende Autotransportwagen zur Auswahl: \n \n".. 
								"Bild 01 = DDm915_fernblau \n" ..
								"Bild 02 = DDm915_oebbDDm915_gruen \n" ..
								"Bild 03 = DDm915_oebb \n" ..
								"Bild 04 = DDm915_verkehrsrot \n" ..
								"Bild 05 = Flachwagen \n" ..
								"Bild 06 = Hccrss328 \n" ..
								"Bild 07 = Hccrss328_ars \n" ..
								"Bild 08 = Laae540 \n" ..
								"Bild 09 = Laaers560 \n" ..
								"Bild 10 = Laeqrss548 \n" ..
								"Bild 11 = Laeqrss550 \n" ..
								"Bild 12 = Laes542 \n" ..
								"Bild 13 = Laes547 \n" ..
								"Bild 14 = Leeks544 \n" ..
								"Bild 15 = Off52 \n" ..
								"Bild 16 = Offhs66 \n" ..
								"Bild 17 = Offs55 \n",
		["mw_model_car_color"] =  "Farbauswahl",
		["mw_model_car_color_tooltip"] =  "diese Auswahl wirkt nur, wenn die PKW Auswahl nicht \"Zufall\" ist. \n \n",
		["mw_color1"] = "Farbe 1",
		["mw_color2"] = "Farbe 2",
		["mw_color3"] = "Farbe 3",
		["mw_color4"] = "Farbe 4",
		["mw_color5"] = "Farbe 5",
		["mw_color6"] = "Farbe 6",
		["mw_color7"] = "Farbe 7",
		["mw_model_car_tooltip"] =  "Auswahl der verladenen PKW abhängig von gewählten Autotransportwagon \n"..
									"nicht jeder PKW kann zu entsprechenden Waggons ausgewählt werden. \n",
		["mw_move_tooltip"] =  "Hiermit können die Wagen etwas nach links bzw. rechts verschoben werden.",
		["mw_move"] =  "verschieben",
		["mw_move_zmeter"] =  "in Zentimeter",
		["mw_left"] =  "links",
		["mw_right"] =  "rechts",
	},
}
end
